# Generated by Django 4.1.1 on 2022-09-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moviemodel',
            table='MOVIE',
        ),
    ]
