# Generated by Django 4.1.1 on 2022-09-29 22:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,10}$', 'should be a-z and 2-10 symbols')])),
                ('city', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'OFFICE',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,10}$', 'should be a-z and 2-10 symbols')])),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='office.officemodel')),
            ],
            options={
                'db_table': 'EMPLOYEE',
            },
        ),
    ]
